### ISSUE TITLE
Link introduction article?

### ISSUE THREAD

**Issue by veox** [JoinColony/solcover#1]
[The article](https://blog.colony.io/code-coverage-for-solidity-eecfa88668c2) contains interesting/important information on the internals and their limitations. It would be nice if linked in this repo - people will eventually get linked directly here.

A link would fit nicely in the [execution section](https://github.com/JoinColony/solcover#execution), probably something like:

```
For more information on intended use and limitations, see the
[introductory article](https://blog.colony.io/code-coverage-for-solidity-eecfa88668c2).
```

... or include a copy like `doc/introduction.html`.

**Comment by area** [comment]
Thanks for pointing out there wasn't a link in that direction! Now included in README.
