### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by cgewecke** [JoinColony/solcover#2]
Hi @area. I'd love to help out with Solcover and have a few PR's I'd like to submit. They're just small fixes for edge cases I'm running into, but I'm also interested in whittling away at the TODO.

Do you have any contribution guidelines or special recommendations?
Would you prefer it if I filed issues before submitting a PR? 

Thanks!
c

**Comment by area** [comment]
Hi there! No real contribution guidelines as yet. For bugfixes, just make sure that any PRs clearly explain the problem they're fixing, and try follow existing style with additions to the code. (I should probably put together an `.eslint` file to make that easier. And looking at it now, I seemed to think TABS were a good idea!?)

For additions of larger features, an issue is probably a good place to start.

**Comment by cgewecke** [comment]
Sounds good.
