### ISSUE TITLE
cross-contract invoke, test result is not the same with truffle

### ISSUE THREAD

**Issue by maiffany** [JoinColony/solcover#20]
Here I come again...
I wanna try to test cross-contract invoking, Just like in java: `new class A` in `class B`.
And I got the two contract.

```
contract Add{
  function sum(uint x, uint y) returns(uint){
    return x+y;
  }
}
contract Sum{
  function func(uint x, uint y) returns(uint){
    Add add = new Add();
    uint re = add.sum(x,y);
    return re;
  }
}
```

Because I call `Add` in `Sum`, so in the `Sum.sol` I have to include`Add` contract inside it.

And now I test this contract in truffle with my own `ethereum` client, it works fine.

![image](https://cloud.githubusercontent.com/assets/5028491/21395038/f1aae692-c7d5-11e6-929a-51e82a4526de.png)

But with solcover, the result is so weired. 

```
instrumenting  ./../originalContracts/Add.sol
instrumenting  ./../originalContracts/Sum.sol
cp: no such file or directory: ./../originalContracts/Migrations.sol
rm: no such file or directory: ./allFiredEvents
Compiling Add.sol...
Compiling Sum.sol...


  Contract: Sum
    1) should return 5 when add 2 and 3
    > No events were emitted

  Contract: Add
    ✓ should return 5 when add 2 and 3


  1 passing (512ms)
  1 failing

  1) Contract: Sum should return 5 when add 2 and 3:
     AssertionError: sum of 2 and 3 is 5: expected '9.1735649321334958107552852973512799782292704141468709142420585807991067901952e+76' to equal 5
      at /Users/maiffany/testcoverage/test/sum.js:6:14
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)



Done
```

My test code is in here: https://github.com/maiffany/mytest/tree/master

**Comment by area** [comment]
I'm sorry to say this is a problem with `testrpc`, not ~`solparse`~`solcover`. There's an [issue logged](https://github.com/ethereumjs/testrpc/issues/149) but no movement on it for quite some time. Given I can reproduce the error with an unpatched `testrpc`, I'm afraid I'm going to close this issue given it's a problem with a dependency that we can't really work around.

**Comment by maiffany** [comment]
Got it! Thank you anyway!
