### ISSUE TITLE
Support for var(x, y)

### ISSUE THREAD

**Issue by area** [JoinColony/solcover#25]
Solidity parser doesn't support this (see https://github.com/ConsenSys/solidity-parser/issues/9), but solparse does. I'm tempted to switch back for now.

**Comment by cgewecke** [comment]
This is hopefully getting fixed in solidity-parser by solparse merging their code in (next week?).

**Comment by area** [comment]
Cool, I'll hold off for now then.

**Comment by cgewecke** [comment]
[Tuples fix](https://github.com/ConsenSys/solidity-parser/pull/60) now very close to being in. They will probably rebuild the parser tomorrow and it should work on whatever ref that is. A couple other fixes were ported from solparse too. Only remaining issue with upgrading to these changes is handling the new node type: `StateVariableDeclaration`.

**Comment by area** [comment]
Great, that'll make me much happier!
