### ISSUE TITLE
"Same line" statements belonging to loop bodies are not reported. 

### ISSUE THREAD

**Issue by cgewecke** [JoinColony/solcover#37]
Istanbul reports a JS statement like this as follows 
```javascript
for(var x = 0; x < 10; x++){ y += 1; }
```
![forloop](https://cloud.githubusercontent.com/assets/7332026/21837287/c7731e80-d77f-11e6-8564-b92ce7d90178.png)

The solcover report:
![forloopsol](https://cloud.githubusercontent.com/assets/7332026/21837563/bef5d728-d781-11e6-9687-20237eb1fdfc.png)

The instrumentation looks like this:
```
Coverage('/Users/user/Sites/sol-coveralls/solcover/test.sol',5);
         StatementCoverage('/Users/user/Sites/sol-coveralls/solcover/test.sol',1);
for(var x = 0; x < 10; x++){  StatementCoverage('/Users/user/Sites/sol-coveralls/solcover/test.sol',2);
y+=1; }
    }
```

If the statement in the body of the `ForStatement` is on its own line, the reporting is correct. Do these same line statements needs their own `Coverage(etc)` event?

**Comment by area** [comment]
I guess this is a philosophical difference more than anything. It is interesting that the istanbul instrumentation shows it being run 10 times though - the natural fix for this would lead to it being marked as run 11 times.

I like the idea of taking Istanbul as the source of 'truth' for what our instrumentation should be doing, but I suspect getting that line being marked as run ten times will prove tricky.

**Comment by cgewecke** [comment]
Right. I'm going to close. No one writes a loop like this anyway.
