### ISSUE TITLE
Uncovered lines in instrumentSolidity.js

### ISSUE THREAD

**Issue by cgewecke** [JoinColony/solcover#43]
[This is what `instrumentSolidity.js`'s coverage report](https://codecov.io/gh/JoinColony/solcover/src/conditional-unit-tests/instrumentSolidity.js) looks like after adding unit tests for conditionals. There are few lines that aren't being run that may be difficult to hit.

+ [L 280 (New)](https://codecov.io/gh/JoinColony/solcover/src/conditional-unit-tests/instrumentSolidity.js#L280) Not completely sure but this might always be on the right hand side of an assignment expression. Possibly unreachable.
+ [L 311 (BinaryExpression)](https://codecov.io/gh/JoinColony/solcover/src/conditional-unit-tests/instrumentSolidity.js#L311) Is there a test that can be written to get inside here? Possibly unreachable.
+ [L 537 and L 541](https://codecov.io/gh/JoinColony/solcover/src/conditional-unit-tests/instrumentSolidity.js#L537) Is this pre- preprocessor bracket handling?

(NB: This issue is book-keeping for changes in the conditional-unit-tests branch which modifies the parsing slightly. The above not necessarily true of master at present.)

**Comment by cgewecke** [comment]
Edit: qualified the above to about conditional-unit-tests branch.

**Comment by area** [comment]
The line `x+2` would get hit by `BinaryExpression`, though obviously that doesn't do anything, and we don't do anything with the instrumentation there... even so, it's valid Solidity, so we should probably support it even if nothing happens there, and check that we do correctly!

`New Contract(args)` can be on a line by itself. You lose the address of the contract, obviously, but is there a reason you'd do stuff in the constructor of a contract and then selfdestruct at the end of the constructor? This would be a very edge case though! Again though, it's technically valid, so we at least need the function there and can test for it.

You're right. `closeBracketStart` is already not used anywhere, and the only branch that uses `closeBracketEnd` is only hit (I believe) when instrumenting the contract before the preprocessor has run on it, so we can remove that too.

I've made a couple of commits that deal with these situations.

**Comment by area** [comment]
And now rebased, so a PR should work properly 👍

**Comment by cgewecke** [comment]
Cool!
