### ISSUE TITLE
Various issues applying solcover to our project.

### ISSUE THREAD

**Issue by maurelian** [JoinColony/solcover#54]
I'm excited about this tool, and think it could be incredibly valuable for the ecosystem, but I'm really struggling to get it to work. After some wrangling, and carefully re-reading the steps, I did manage to get it working with the basic truffle metacoin project. 

However, for the actual project I need to run this on, I'm still hitting a wall. I'll outline my use case, some of what I've done, and where I'm now stuck. Thanks in advance for your assistance. 

I'm running:
* node 6.9.1
* truffle v3.2.1

The project is here: https://github.com/uport-project/uport-proxy, and has some fairly large contracts in it, but none which cannot be deployed as is.

Issues I've bypassed: 
* The default account was running out of funds during the deployment phase, so rather than the `    gasPrice: 20e9,` shown in the README, I've used `gasPrice: 0x2`
* Contract inheritance is broken during the instrumentation process, an error is generated during compilation due to the duplicate declaration of the events. I manually combined the contracts to fix. 
* My tests require a lot of accounts, so I modified the testrpc flags in `./runCoveredTests.js` to include `--accounts 25`.

After all this, when I finally run `node ./runCoveredTests.js` from within the `solcover` directory in my project, there is a long pause after the last contract is compiled, but I then eventually get: 

```Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/primary/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/primary/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/primary/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/primary/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/Users/primary/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/Users/primary/.nvm/versions/node/v6.9.1/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:414:24)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:346:9)
    at emitNone (events.js:91:20)
Done
```

I noticed that after this, there is a coverage report generated, but it's clearly incomplete, and not based on the actual tests. 

Things I've tried to address this:

* run `lsof -i tcp:8545`, there is no other activity on that port. 
* In order to get a bit more information, I commented out [this line](https://github.com/JoinColony/solcover/blob/master/runCoveredTests.js#L20), and instead ran the command in a terminal. 
`./node_modules/ethereumjs-testrpc/bin/testrpc --gasLimit 0xfffffffffffff --gasPrice 0x1 --accounts 25`.   (The `runCoveredTests` script had already run so it's patched). Based on what I've seen there, the `Error: Invalid JSON RPC response: ""` message is appearing exactly 120 seconds after the first `eth_sendTransaction` message appears in the testrpc terminal.

At the moment I'm assuming that web3.js is timing out during the deployment of some particularly large contract, and I'm trying to figure out how to prevent that. I've also added the `--verbose-rpc` flag to the truffle test command, hopefully that will help point to the contract causing the issue.  I will update.

**Comment by cgewecke** [comment]
@maurelian Thanks for this issue and sorry its been so difficult to get working. Development here has been blocked for a couple months for reasons discussed in #51. 

Is there any chance you could provide a link to the uport fork or branch where you're trying to get solcover to work so we can help debug it? 

Not completely sure but based on the error msg it's possible that the patch solcover generates for ethereumjs-vm has fallen out of sync and needs to be upgraded.

**Comment by maurelian** [comment]
Thanks @cgewecke. 

Here's a repo/branch with some changes I've tried to make to get it working: 
https://github.com/maurelian/uport-proxy/tree/modifyContract

The solcover submodule is my own fork with a few small changes to the run script. 

Also, I talked with Tim Coulter in the truffle gitter: 

```
Tim: Invalid Error: Invalid JSON RPC response: “” usually means it can’t connect to the correct Ethereum network via the host and port you provided. Why it’s exactly 120 seconds seems less clear to me. Is the TestRPC giving you transaction output - i.e., about 5 lines printed to the console about the transaction itself, gas cost, error, etc?

Me: no, eth_sendtransaction is the last thing I get from testrpc

Tim: Are you running in forked mode?

Me:  No. But if we think the issue might be on testrpc, I'm trying to get solcover working, which applies a patch to testrpc.

Tim: Hmm. If the TestRPC isn’t printing more tx output, then ya my guess is it’s a TestRPC issue. But if its patching it, I can’t vouch for what it’s doing.

Me:  yeah, wouldn't ask you to support that, but it's good to be pointed in the right direction.

Tim: I’ve only ever seen that error output immediately.
So without any more context, my guess is solcover.
```

**Comment by cgewecke** [comment]
Cool, thanks. Taking a peek at it now.

**Comment by cgewecke** [comment]
@maurelian When you run `truffle test` are you getting this error?
```
Compiling ./contracts/IdentityFactory.sol...
Compiling ./contracts/IdentityFactoryWithRecoveryKey.sol...
Compiling ./contracts/Lib1.sol...
Compiling ./contracts/MetaTxController.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/Owned.sol...
Compiling ./contracts/Proxy.sol...
Compiling ./contracts/RecoverableController.sol...
Compiling ./contracts/RecoveryQuorum.sol...
Compiling ./contracts/TestRegistry.sol...
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/Users/user/Sites/uport-proxy/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/Users/user/Sites/uport-proxy/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/Sites/uport-proxy/node_modules/bitcore-mnemonic/lib/mnemonic.js:3:15)
```

**Comment by cgewecke** [comment]
Resolved the above by manually removing `bitcore-lib` from `ethereum-bip44` and `eth-signer` in `node_modules`.

Seeing a couple failing tests for `Contract: Owned` in the `modifyContracts` branch. When I comment them out, the rest of the suite passes. About to check passing tests with solcover.

![screen shot 2017-03-26 at 4 36 58 pm](https://cloud.githubusercontent.com/assets/7332026/24336347/8a27f3f4-1242-11e7-8a1f-df42b938a7a8.png)

**Comment by cgewecke** [comment]
@maurelian I think your intuition about it being a large contract problem is right - Truffle isn't able to deploy the instrumented version of `RecoveryQuorum.sol` no matter how much gas is thrown at it. I'm going to look at this more tomorrow.

**Comment by maurelian** [comment]
@cgewecke very sorry about this issue: 

```Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.```

It looks like some of my local changes didn't get pushed. I will do that today and let you know with clear instructions for reaching the point I'm at.  Thanks so much for your help  on this, it would be really valuable if we could hack out a meaningful coverage measurement here.

**Comment by cgewecke** [comment]
@maurelian It's no problem - I just followed the steps in your initial description and have been able to reproduce the same behavior. I'm able to get all instrumented contracts except `RecoveryQuorum.sol` to deploy - which hangs on send_transaction. I've also moved the Lib1 function into RQ and removed deployment linking to verify that its not related to that. I think you're right that the source is something in web3 or testrpc but obviously also caused by injecting so many events (or just lines?) into the contract.

**Comment by cgewecke** [comment]
@maurelian I think I've made a little headway on this with the following steps:
+ commenting out the tests to focus on deployment
+ running `truffle test` against the uport contracts with only `RecoveryQuorum.sol` instrumented.
+ manually logging the vm behavior on deployment (it goes into an infinite loop) 
+ commenting out the instrumentation events in `RecoveryQuorum.sol`'s constructor (it deploys!)
+ repeating the above for `RecoverableController.sol` *without* removing instrumentation events from the constructor (it also deploys . . .)

It looks like the problem is the loop in the RQ constructor on deployment and the absence of arguments being passed to it in the deploy script. Injecting all the events is maybe just unmasking that, segfault-style?

I've been able to get through the deployment stage by manually installing `solc 0.4.4` on Truffle and changing [this line](https://github.com/maurelian/uport-proxy/blob/modifyContract/migrations/2_deploy_contracts.js#L18) in the migrations deploy script to
```javascript
deployer.deploy(RecoveryQuorum, '0x0', []);
```   
And I've been able to generate coverage reports with only a couple problems: the instrumented tests fail at IdentityFactory: `Created ID should have the following behavior` - possibly because that test is so heavy (it generates a huge number of events), and where the PROXY_GAS_OVERHEAD is being checked in uportProxyIntegration. (That makes sense since the events use more gas).

Will open a PR in your fork of solcover shortly with the `runCoveredScripts.js` version I've been using plus the generated reports so you can check this on your end.

**Comment by maurelian** [comment]
Wow @cgewecke, that's quite impressive! Thank you so much for doing that. 

Without having seen your changes, I think it would be fine to simply remove the  instrumentation from the constructor in `RecoveryQuorum.sol`. It might throw off the output slightly but not too bad. So strange that it causes an infinite loop though, how were you able to 'manually log the vm behaviour'?

I unfortunately won't be able to look any more tonight, but I'll try to take another crack at it again tomorrow from wherever you leave off. :)

**Comment by cgewecke** [comment]
Can't seem to PR cleanly but here's a link to a [uport branch in the main fork](https://github.com/JoinColony/solcover/tree/uport). Am using 
```
gasPrice: 0x01,
gas: 0xffffffffffffff
```
in the Truffle config and running the solcover script as is, without launching testrpc separately.  I think as long as the line you added to invoke truffle uses an older version of solc that doesn't have the issues with events everything should work. Please let me know if there are still problems.

Any reports about discrepancies between what the tests run and the coverage are more than welcome.

**Comment by maurelian** [comment]
Just took a quick look at the report, except for sacrificing coverage measurement of `Owned.sol` it looks excellent! I'll take a closer look at the changes tomorrow, and also try using a truffle on an older version of solc. 

Much appreciated!

**Comment by cgewecke** [comment]
@maurelian Luckily for solcover it seems okay to have events in the constructor but this problem was weird . . . It looks like if you deploy a contract in Truffle without specifying the constructor arguments it's not guaranteed that they are nulled out. In your regular tests, when you deploy, the loop condition in the RQ constructor happens to evaluate to false. But when the contract is instrumented it doesn't! The loop runs until it's out of gas.

I'm not sure what to make of this but it feels a little non-deterministic and could cause weird behavior in real deployments? Maybe not. 

Have a good night! Thanks @maurelian. 👍

**Comment by mathcrypto** [comment]
i get the error cannot specify current network

**Comment by mathcrypto** [comment]
i used the suggested truffle.js file 
module.exports = {
  rpc: {
    host: 'localhost',
    gasPrice: 20e9,
    gas: 0xfffffff,
  }
 };

**Comment by mathcrypto** [comment]
when i run the command suggested node ./runCoveredTests.js
I get this error 
rm: no such file or directory: ./allFiredEvents
Unknown network "test". See your Truffle configuration file for available networks.
fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './allFiredEvents'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.<anonymous> (/Users/amira/myproject/solcover/runCoveredTests.js:50:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)

**Comment by maurelian** [comment]
@mathcrypto I think that's the config for truffle v2.x. 

Try this in your truffle.js file: 

```
module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*"
    },
    test: {
      host: "localhost",
      port: 8545,
      network_id: "*",
      gasPrice: 0x2,
      gas: 0xfffffff,
    }
  }
};
```

If that's not it, I'd suggest opening a new issue to provide more clarity.
