### ISSUE TITLE
Instrumentation breaks constructor call chained to a method call

### ISSUE THREAD

**Issue by cgewecke** [JoinColony/solcover#60]
This problem came up covering the ENS contracts. When a contract is instantiated using an address and one of its methods is immediately invoked by chaining - e.g:
```javascript
contract Chainable {
    function chainWith(uint y, uint z){}
}

contract Test {
    function Test(){
        Chainable(0x00).chainWith(3, 4);
    }
}
```
the AST will have nested `CallExpression` nodes and the instrumenter will mistakenly inject two statement events:
```
function Test(){
__FunctionCoverageChainable('test.sol',3);
__CoverageChainable('test.sol',13);
         __StatementCoverageChainable('test.sol',3);
 __StatementCoverageChainable('test.sol',1);
Chainable().chainWith __StatementCoverageChainable('test.sol',2);
(3, 4);
    }
}
```
resulting in:
```
 Error: Instrumented solidity invalid: :27:27: Error: Expected token Semicolon got 'Identifier'
Chainable().chainWith __StatementCoverageChainable('test.sol',2);
```

Have a pushed a fix and compilation check unit test for this case to truffle3 branch with [this commit](https://github.com/JoinColony/solcover/commit/440bd8b602a71b5b900cd4e9e009e0a23006dbbf)

**Comment by cgewecke** [comment]
Previous fix needed another [fix](https://github.com/JoinColony/solcover/commit/4b627f6b9e9262c9dd981f9514be4e49630162c1) Was crashing on [this line in the Chronobank SmartContracts repo](https://github.com/ChronoBank/SmartContracts/blob/master/contracts/ChronoBankAssetProxy.sol#L303):
```
_getAsset().__process.value(msg.value)(msg.data, msg.sender);
```

Have added some coverage tests for CallExpressions as well to try to make sure events are being injected correctly.

**Comment by area** [comment]
Fixed in [solidity-coverage](https://github.com/sc-forks/solidity-coverage).
