### ISSUE TITLE
Empty contract bodies break ContractOrLibraryStatement parsing

### ISSUE THREAD

**Issue by cgewecke** [JoinColony/solcover#61]
zeppelin-solidity now has an empty bodied contract that looks like this:
```javascript
pragma solidity ^0.4.8;

import "./HasNoEther.sol";
import "./HasNoTokens.sol";
import "./HasNoContracts.sol";

contract NoOwner is HasNoEther, HasNoTokens, HasNoContracts {
}
```
which breaks `parse.js` [here](https://github.com/JoinColony/solcover/blob/master/parse.js#L191) .

Fix for this and a coverage unit test for the case are pushed to truffle3 branch in [this commit](https://github.com/JoinColony/solcover/commit/21d3c04ead15dd17d81aff2662ecc642d42a5ae6)

**Comment by area** [comment]
Fixed in [solidity-coverage](https://github.com/sc-forks/solidity-coverage), I believe.
